sayit.data = [
    ["I am a boy", "you are a student", "I am a teacher", "she is a girl", "how old are you?", "john is a man", "I am happy", "english is easy"],
    ["I have a pencil", "You have a pair of scissors", "Do you have any pencils?", "How many sisters do you have?", "We had a car waiting outside", "I have something for you", "I had no time to see you", "Was that a pencil?"],
    ["There is not any book on the table", "Is there a Miss Lee staying here?", "What is there on the table?", "There are two pencils in my box", "There won’t be many teachers going to the party", "Will there be a birthday party in the home?", "There’s a telephone call for you"],
    ["I open the door", "Have you seen him?", "Where did you see him?", "I have lived in Shanghai for a long time", "What do you need it for?", "I have bought the car", "The door has been opened", "Has your brother come from Paris?"],
    ["I must get myself a new pair of glasses", "Get me two pounds of tomatoes", "It’s getting dark", "You’re getting fat", "Have you got a match?", "He said the telegram had arrived at noon", "She promised she would reserve a room for me", "I’ve got to go now"],
    ["I want you to tell me this", "You have to share it with other tenants", "I’d like to be called at 7", "You‘d better wear a light jacket", "Most scientists tend to agree with me", "Today we are going to hear report", "We should be able to resolve our difference", "All this is due to our change in teaching methods"],
    ["Look at the blackboard", "Thank you very much", "Tell me in your own words", "Could you tell me the way to the station?", "They can be divided into three groups", "You must know the sound of each letter in the English alphabet", "We may have good reason to be proud of ourselves", "May I take this chair?"],
    ["I won’t believe it unless I see it with my own eyes", "I wish I could go and visit my aunt tomorrow", "I’m sorry to interrupt you", "I wish I could go and visit my aunt tomorrow", "I gave the students a chance to say a few words too", "I gave the students a chance to say a few words too", "I’ve got a taxi waiting outside", "I wish I could talk to you about art"]
]
